[package]
name = "wisp-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
build = "build.rs"

[dependencies]
wisp-core = { path = "../wisp-core" }
wisp-pe-loader = { path = "../wisp-pe-loader" }
libc.workspace = true
thiserror.workspace = true

[build-dependencies]
cc = "1"
