use std::sync::Arc;
use bytemuck::{Pod, Zeroable};
use wgpu::util::DeviceExt;
use winit::{dpi::PhysicalSize, window::Window};
use crate::camera::{Camera, Mat4, DEFAULT_FOV};
use crate::physics::{Food, Fly, ARENA_HALF_SIZE};
const STRIDE:u64=256;
#[repr(C)]#[derive(Clone,Copy,Pod,Zeroable)]struct Vertex{p:[f32;3]}
#[repr(C)]#[derive(Clone,Copy,Pod,Zeroable)]struct Object{vp:[f32;16],model:[f32;16],color:[f32;4]}
const CUBE_V:&[Vertex]=&[Vertex{p:[-.5,-.5,-.5]},Vertex{p:[.5,-.5,-.5]},Vertex{p:[.5,.5,-.5]},Vertex{p:[-.5,.5,-.5]},Vertex{p:[-.5,-.5,.5]},Vertex{p:[.5,-.5,.5]},Vertex{p:[.5,.5,.5]},Vertex{p:[-.5,.5,.5]}];
const CUBE_I:&[u16]=&[0,1,2,2,3,0,4,6,5,6,7,4,0,4,7,7,3,0,1,5,6,6,2,1,3,2,6,6,7,3,0,1,5,5,4,0];
const FOOD_V:&[Vertex]=&[Vertex{p:[0,.7,0]},Vertex{p:[.7,0,0]},Vertex{p:[0,0,.7]},Vertex{p:[-.7,0,0]},Vertex{p:[0,0,-.7]},Vertex{p:[0,-.7,0]}];
const FOOD_I:&[u16]=&[0,1,2,0,2,3,0,3,4,0,4,1,5,2,1,5,3,2,5,4,3,5,1,4];
const SHADER:&str=r#"struct Object{vp:mat4x4<f32>,model:mat4x4<f32>,color:vec4<f32>};@group(0)@binding(0)var<uniform>o:Object;struct Out{@builtin(position)p:vec4<f32>};@vertex fn vs(@location(0)p:vec3<f32>)->Out{var x:Out;x.p=o.vp*o.model*vec4<f32>(p,1.0);return x}@fragment fn fs()->@location(0)vec4<f32>{return o.color}"#;

pub struct Renderer{surface:wgpu::Surface<'static>,device:wgpu::Device,queue:wgpu::Queue,config:wgpu::SurfaceConfiguration,size:PhysicalSize<u32>,pipeline:wgpu::RenderPipeline,depth:wgpu::TextureView,cube_v:wgpu::Buffer,cube_i:wgpu::Buffer,food_v:wgpu::Buffer,food_i:wgpu::Buffer,ub:wgpu::Buffer,bg:wgpu::BindGroup}
#[derive(Debug)]pub enum RenderError{AdapterUnavailable,Device(String),Surface(String)}
impl std::fmt::Display for RenderError{fn fmt(&self,f:&mut std::fmt::Formatter<'_>)->std::fmt::Result{match self{Self::AdapterUnavailable=>write!(f,"no compatible GPU adapter"),Self::Device(e)=>write!(f,"GPU device: {e}"),Self::Surface(e)=>write!(f,"surface: {e}")}}}impl std::error::Error for RenderError{}
impl Renderer{
 pub async fn new(window:Arc<Window>)->Result<Self,RenderError>{
  let size=window.inner_size();let instance=wgpu::Instance::new(wgpu::InstanceDescriptor{backends:wgpu::Backends::VULKAN|wgpu::Backends::GL,..Default::default()});let surface=instance.create_surface(window).map_err(|e|RenderError::Surface(e.to_string()))?;
  let adapter=instance.request_adapter(&wgpu::RequestAdapterOptions{power_preference:wgpu::PowerPreference::LowPower,compatible_surface:Some(&surface),force_fallback_adapter:false}).await.ok_or(RenderError::AdapterUnavailable)?;
  log::info!("Wisp GPU: {} ({:?})",adapter.get_info().name,adapter.get_info().backend);
  let (device,queue)=adapter.request_device(&wgpu::DeviceDescriptor{label:Some("wisp"),required_features:wgpu::Features::empty(),required_limits:wgpu::Limits::downlevel_defaults(),memory_hints:wgpu::MemoryHints::Performance},None).await.map_err(|e|RenderError::Device(e.to_string()))?;
  let caps=surface.get_capabilities(&adapter);let format=caps.formats.iter().copied().find(|f|f.is_srgb()).unwrap_or(caps.formats[0]);let mode=if caps.present_modes.contains(&wgpu::PresentMode::Fifo){wgpu::PresentMode::Fifo}else{caps.present_modes[0]};let config=wgpu::SurfaceConfiguration{usage:wgpu::TextureUsages::RENDER_ATTACHMENT,format,width:size.width.max(1),height:size.height.max(1),present_mode:mode,alpha_mode:caps.alpha_modes[0],view_formats:vec![],desired_maximum_frame_latency:2};surface.configure(&device,&config);
  let shader=device.create_shader_module(wgpu::ShaderModuleDescriptor{label:Some("shader"),source:wgpu::ShaderSource::Wgsl(SHADER.into())});let ub=device.create_buffer(&wgpu::BufferDescriptor{label:Some("objects"),size:STRIDE*8,usage:wgpu::BufferUsages::UNIFORM|wgpu::BufferUsages::COPY_DST,mapped_at_creation:false});
  let bl=device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor{label:Some("object-layout"),entries:&[wgpu::BindGroupLayoutEntry{binding:0,visibility:wgpu::ShaderStages::VERTEX,ty:wgpu::BindingType::Buffer{ty:wgpu::BufferBindingType::Uniform,has_dynamic_offset:true,min_binding_size:None},count:None}]});let bg=device.create_bind_group(&wgpu::BindGroupDescriptor{label:Some("object-bind"),layout:&bl,entries:&[wgpu::BindGroupEntry{binding:0,resource:ub.as_entire_binding()}]});let pl=device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor{label:Some("layout"),bind_group_layouts:&[&bl],push_constant_ranges:&[]});
  let pipeline=device.create_render_pipeline(&wgpu::RenderPipelineDescriptor{label:Some("pipeline"),layout:Some(&pl),vertex:wgpu::VertexState{module:&shader,entry_point:"vs",buffers:&[wgpu::VertexBufferLayout{array_stride:12,step_mode:wgpu::VertexStepMode::Vertex,attributes:&[wgpu::VertexAttribute{offset:0,shader_location:0,format:wgpu::VertexFormat::Float32x3}]}]},fragment:Some(wgpu::FragmentState{module:&shader,entry_point:"fs",targets:&[Some(wgpu::ColorTargetState{format,blend:None,write_mask:wgpu::ColorWrites::ALL})]}),primitive:wgpu::PrimitiveState{cull_mode:Some(wgpu::Face::Back),..Default::default()},depth_stencil:Some(wgpu::DepthStencilState{format:wgpu::TextureFormat::Depth32Float,depth_write_enabled:true,depth_compare:wgpu::CompareFunction::Less,stencil:Default::default(),bias:Default::default()}),multisample:Default::default(),multiview:None});
  let depth=Self::make_depth(&device,config.width,config.height);let cube_v=device.create_buffer_init(&wgpu::util::BufferInitDescriptor{label:Some("cube-v"),contents:bytemuck::cast_slice(CUBE_V),usage:wgpu::BufferUsages::VERTEX});let cube_i=device.create_buffer_init(&wgpu::util::BufferInitDescriptor{label:Some("cube-i"),contents:bytemuck::cast_slice(CUBE_I),usage:wgpu::BufferUsages::INDEX});let food_v=device.create_buffer_init(&wgpu::util::BufferInitDescriptor{label:Some("food-v"),contents:bytemuck::cast_slice(FOOD_V),usage:wgpu::BufferUsages::VERTEX});let food_i=device.create_buffer_init(&wgpu::util::BufferInitDescriptor{label:Some("food-i"),contents:bytemuck::cast_slice(FOOD_I),usage:wgpu::BufferUsages::INDEX});Ok(Self{surface,device,queue,config,size,pipeline,depth,cube_v,cube_i,food_v,food_i,ub,bg})
 }
 fn make_depth(d:&wgpu::Device,w:u32,h:u32)->wgpu::TextureView{d.create_texture(&wgpu::TextureDescriptor{label:Some("depth"),size:wgpu::Extent3d{width:w.max(1),height:h.max(1),depth_or_array_layers:1},mip_level_count:1,sample_count:1,dimension:wgpu::TextureDimension::D2,format:wgpu::TextureFormat::Depth32Float,usage:wgpu::TextureUsages::RENDER_ATTACHMENT,view_formats:&[]}).create_view(&wgpu::TextureViewDescriptor::default())}
 pub fn size(&self)->PhysicalSize<u32>{self.size}
 pub fn resize(&mut self,s:PhysicalSize<u32>){if s.width==0||s.height==0{return;}self.size=s;self.config.width=s.width;self.config.height=s.height;self.surface.configure(&self.device,&self.config);self.depth=Self::make_depth(&self.device,s.width,s.height);}
 fn write(&self,n:u32,vp:Mat4,m:Mat4,c:[f32;4]){let u=Object{vp:vp.to_cols_array(),model:m.to_cols_array(),color:c};self.queue.write_buffer(&self.ub,n as u64*STRIDE,bytemuck::bytes_of(&u));}
 pub fn render(&mut self,fly:&Fly,food:&Food)->Result<(),wgpu::SurfaceError>{let f=fly.forward();let cam=Camera{position:[fly.position[0]-f[0]*5.0,3.0,fly.position[2]-f[2]*5.0],target:[fly.position[0]+f[0]*1.5,0.25,fly.position[2]+f[2]*1.5],aspect:self.size.width as f32/self.size.height.max(1) as f32,fov_y:DEFAULT_FOV,near:0.1,far:40.0};let vp=cam.view_projection();self.write(0,vp,Mat4::translation(0.0,-0.3,0.0).mul(Mat4::scale(16.0,0.5,16.0)),[0.08,0.11,0.09,1.0]);self.write(1,vp,Mat4::translation(0.0,0.75,-ARENA_HALF_SIZE).mul(Mat4::scale(16.0,1.5,0.35)),[0.15,0.18,0.17,1.0]);self.write(2,vp,Mat4::translation(0.0,0.75,ARENA_HALF_SIZE).mul(Mat4::scale(16.0,1.5,0.35)),[0.15,0.18,0.17,1.0]);self.write(3,vp,Mat4::translation(-ARENA_HALF_SIZE,0.75,0.0).mul(Mat4::scale(0.35,1.5,16.0)),[0.15,0.18,0.17,1.0]);self.write(4,vp,Mat4::translation(ARENA_HALF_SIZE,0.75,0.0).mul(Mat4::scale(0.35,1.5,16.0)),[0.15,0.18,0.17,1.0]);self.write(5,vp,Mat4::translation(fly.position[0],fly.position[1],fly.position[2]).mul(Mat4::rotation_y(fly.rotation_y)).mul(Mat4::scale(0.8,0.28,1.3)),[0.60,0.20,0.08,1.0]);self.write(6,vp,Mat4::translation(food.position[0],food.position[1],food.position[2]).mul(Mat4::scale(0.6,0.6,0.6)),[0.95,0.72,0.10,1.0]);let frame=self.surface.get_current_texture()?;let view=frame.texture.create_view(&wgpu::TextureViewDescriptor::default());let mut enc=self.device.create_command_encoder(&wgpu::CommandEncoderDescriptor{label:Some("frame")});{let mut p=enc.begin_render_pass(&wgpu::RenderPassDescriptor{label:Some("arena"),color_attachments:&[Some(wgpu::RenderPassColorAttachment{view:&view,resolve_target:None,ops:wgpu::Operations{load:wgpu::LoadOp::Clear(wgpu::Color{r:0.015,g:0.020,b:0.028,a:1.0}),store:wgpu::StoreOp::Store}})],depth_stencil_attachment:Some(wgpu::RenderPassDepthStencilAttachment{view:&self.depth,depth_ops:Some(wgpu::Operations{load:wgpu::LoadOp::Clear(1.0),store:wgpu::StoreOp::Store}),stencil_ops:None}),timestamp_writes:None,occlusion_query_set:None});p.set_pipeline(&self.pipeline);p.set_vertex_buffer(0,self.cube_v.slice(..));p.set_index_buffer(self.cube_i.slice(..),wgpu::IndexFormat::Uint16);for n in 0..6{p.set_bind_group(0,&self.bg,&[n*STRIDE as u32]);p.draw_indexed(0..CUBE_I.len() as u32,0,0..1);}p.set_vertex_buffer(0,self.food_v.slice(..));p.set_index_buffer(self.food_i.slice(..),wgpu::IndexFormat::Uint16);p.set_bind_group(0,&self.bg,&[6*STRIDE as u32]);p.draw_indexed(0..FOOD_I.len() as u32,0,0..1);}self.queue.submit(Some(enc.finish()));frame.present();Ok(())}
}
